package view.com.raven.component;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.io.File;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

public class CardBackupSistema extends javax.swing.JPanel {

    public CardBackupSistema() {
        initComponents();
        carregarTabela();
    }

    String location = null;
    String filename;
    private static int proximoId = 1; // ID inicial
    private static final String ARQUIVO = "backup_log.txt";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#1CB5E0"), 0, getHeight(), Color.decode("#000046"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table_backup = new view.com.raven.swing.Table();
        TXT_BACKUP = new javax.swing.JLabel();
        BTN_GERAR_BACKUP = new javax.swing.JButton();

        table_backup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATA"
            }
        ));
        jScrollPane2.setViewportView(table_backup);

        BTN_GERAR_BACKUP.setText("Gerar Backup");
        BTN_GERAR_BACKUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GERAR_BACKUPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_GERAR_BACKUP)
                    .addComponent(TXT_BACKUP, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TXT_BACKUP, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_GERAR_BACKUP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Método para criar uma pasta
    public static void criarPasta(String caminho) {
        File pasta = new File(caminho);

        // Verifica se a pasta já existe
        if (!pasta.exists()) {
            boolean criada = pasta.mkdir(); // Cria a pasta
            if (criada) {
//                System.out.println("Pasta criada com sucesso!");
            } else {
//                System.out.println("Falha ao criar a pasta.");
            }
        } else {
//            JOptionPane.showMessageDialog(null, "A pasta já existe.\n");
        }
    }

    // Método para ler o conteúdo da pasta
    public static void lerConteudoPasta(String caminho) {
        File pasta = new File(caminho);

        // Verifica se a pasta existe
        if (pasta.exists() && pasta.isDirectory()) {
            String[] conteudo = pasta.list(); // Lista os arquivos e pastas dentro da pasta
            if (conteudo != null && conteudo.length > 0) {
                System.out.println("Conteúdo da pasta:");
                for (String item : conteudo) {
                    System.out.println(item);
                }
            } else {
//                System.out.println("A pasta está vazia.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "A pasta não existe ou não é um diretório.\n");
        }
    }

    public static void gerarBackup(String filename) {
        // Caminho do mysqldump e outros parâmetros
        String mysqldumpPath = "C:/Program Files/MySQL/MySQL Server 8.0/bin/mysqldump.exe";
        String host = "localhost";
        String user = "root";
        String password = "#Wiccan13#";
        String database = "tefe";
        String port = "3306";

        // Comando completo do mysqldump
        String command = String.format("\"%s\" -v -v -v --host=%s --user=%s --password=%s --port=%s --protocol=tcp --force --allow-keywords --compress --add-drop-table --default-character-set=latin1 --hex-blob --result-file=%s --databases %s",
                mysqldumpPath, host, user, password, port, filename, database);

        ProcessBuilder processBuilder = new ProcessBuilder(command.split(" "));

        // Definir o diretório de trabalho, caso necessário
        processBuilder.directory(new java.io.File("C:/"));

        try {
            // Iniciar o processo
            Process process = processBuilder.start();

            // Captura de erros e saída padrão do processo
            BufferedReader errorReader = new BufferedReader(new InputStreamReader(process.getErrorStream()));
            BufferedReader outputReader = new BufferedReader(new InputStreamReader(process.getInputStream()));

            String line;
            StringBuilder output = new StringBuilder();
            StringBuilder errors = new StringBuilder();

            // Captura da saída do processo
            while ((line = outputReader.readLine()) != null) {
                output.append(line).append("\n");
            }

            // Captura dos erros do processo
            while ((line = errorReader.readLine()) != null) {
                errors.append(line).append("\n");
            }

            // Aguarda o término do processo
            int processComplete = process.waitFor();

            // Verifica o resultado
            if (processComplete == 0) {
                JOptionPane.showMessageDialog(null, "Backup Gerado com sucesso!\n" + output.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao gerar Backup!\nErros: " + errors.toString());
            }
        } catch (IOException | InterruptedException e) {
            JOptionPane.showMessageDialog(null, "Erro ao executar o comando: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void gerarLogBackup() {
        int proximoId = obterProximoId();

        // Formata a data atual
        String dataFormatada = new SimpleDateFormat("dd/MM/yyyy").format(new Date());
        String linha = proximoId + "," + dataFormatada;

        // Grava no arquivo
        try ( BufferedWriter writer = new BufferedWriter(new FileWriter(ARQUIVO, true))) {
            writer.write(linha);
            writer.newLine();
//            JOptionPane.showMessageDialog(this, "Backup gerado com ID: " + proximoId);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao gravar log backup: " + ex.getMessage());
        }
    }

    private int obterProximoId() {
        int ultimoId = 0;
        try ( BufferedReader reader = new BufferedReader(new FileReader(ARQUIVO))) {
            String linha;
            while ((linha = reader.readLine()) != null) {
                String[] partes = linha.split(",");
                if (partes.length >= 1) {
                    ultimoId = Integer.parseInt(partes[0]);
                }
            }
        } catch (FileNotFoundException e) {
            // Primeira execução, arquivo ainda não existe
            return 1;
        } catch (IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro ao ler arquivo: " + e.getMessage());
        }
        return ultimoId + 1;
    }

    private void carregarTabela() {
        String[] colunas = {"ID", "Data"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);

        try ( BufferedReader reader = new BufferedReader(new FileReader(ARQUIVO))) {
            String linha;
            while ((linha = reader.readLine()) != null) {
                String[] dados = linha.split(",");
                if (dados.length == 2) {
                    Vector<String> linhaTabela = new Vector<>();
                    linhaTabela.add(dados[0]);
                    linhaTabela.add(dados[1]);
                    modelo.addRow(linhaTabela);
                }
            }
            table_backup.setModel(modelo);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
        }
    }

    private void BTN_GERAR_BACKUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GERAR_BACKUPActionPerformed
        String caminhoPasta = "C:/Backup"; // Caminho da pasta a ser criada e lida

        // Criar a pasta
        criarPasta(caminhoPasta);

        String filename = "C:/Backup/tefe.sql"; // Defina o caminho do arquivo de backup
        gerarBackup(filename);

        // Ler o conteúdo da pasta
        lerConteudoPasta(caminhoPasta);

        gerarLogBackup();
        carregarTabela();

        System.out.println("Registros gravados com sucesso.");
    }//GEN-LAST:event_BTN_GERAR_BACKUPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_GERAR_BACKUP;
    private javax.swing.JLabel TXT_BACKUP;
    private javax.swing.JScrollPane jScrollPane2;
    private view.com.raven.swing.Table table_backup;
    // End of variables declaration//GEN-END:variables
}
